version: "3.8"

services:
  db:
    image: postgres:15
    container_name: bekhan-db
    environment:
      POSTGRES_DB: bekhan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "2345:5432"

  app:
    build: .
    container_name: bekhan-daulet-app
    ports:
      - "3333:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bekhan
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
